import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import Header from "../../components/hulu/Header";
import Nav from "../../components/hulu/Nav";
import Results from "../../components/hulu/Results";
import requests from "../../services/hulu/requests";

export const getServerSideProps = async (context: any) => {
    const genre = context.query.genre;
    //@ts-ignore
    const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then((res) =>
        res.json()
    );
    return {
        props: {
            results: request.results,
        },
    };
};

const Home: NextPage = ({ results }: any) => {
    return (
        <div className="text-gray-300">
            <Head>
                <title>Hulu 2.0</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Nav />
            <Results results={results} />

            <footer></footer>
            <style jsx global>
                {`
                    body {
                        background: #06202a;
                    }
                `}
            </style>
        </div>
    );
};

export default Home;
