import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className="text-4xl">Hello World!</h1>
                <div className="columns-2 w-96 mx-auto">
                    <p>Well, let me tell you something, ...</p>
                    <p className="break-after-column">Sure, go ahead, laugh...</p>
                    <p>Maybe we can live without...</p>
                    <p>Look. If you think this is...</p>
                </div>
                <button disabled>TEST</button>
            </main>

            <footer></footer>
        </div>
    );
};

export default Home;
